version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: flow-budget-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: flow-budget-dev
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
